require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, 'public')));

// Email Notification Route
app.post('/api/contact', async (req, res) => {
  const { name, phone, email, country, service, message } = req.body;

  if (!name || !phone || !email) {
    return res.status(400).json({ error: 'Name, email, and phone are required.' });
  }

  // Configure Nodemailer transporter
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: process.env.SMTP_PORT || 587,
    secure: process.env.SMTP_SECURE === 'true', // true for 465, false for other ports
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  // Setup HTML email template
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; border: 1px solid #C0392B; border-radius: 8px; overflow: hidden;">
      <div style="background: linear-gradient(90deg, #C0392B, #E67E22); padding: 20px; text-align: center; color: white;">
        <h1 style="margin: 0;">New Enquiry Received</h1>
        <p style="margin: 5px 0 0;">Precious Albidin Grand Tours - Turkey</p>
      </div>
      <div style="padding: 20px; line-height: 1.6; color: #333;">
        <p>A new enquiry has been submitted through the website contact form:</p>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Name:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #eee;">${name}</td></tr>
          <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Phone/WhatsApp:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #eee;">${phone}</td></tr>
          <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Email:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #eee;">${email}</td></tr>
          <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Country:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #eee;">${country || 'Not specified'}</td></tr>
          <tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;"><strong>Service:</strong></td><td style="padding: 8px 0; border-bottom: 1px solid #eee;">${service || 'Not specified'}</td></tr>
        </table>
        <div style="margin-top: 20px; padding: 15px; background: #FFF8F0; border-left: 4px solid #F39C12;">
          <strong>Message:</strong><br>
          ${message || 'No message provided.'}
        </div>
      </div>
      <div style="background: #FDF6EC; padding: 15px; text-align: center; font-size: 12px; color: #888;">
        &copy; 2025 Precious Albidin Grand Tours. This email was generated by the website.
      </div>
    </div>
  `;

  const mailOptions = {
    from: `"${name}" <${process.env.EMAIL_USER}>`, // The sender must be the EMAIL_USER for many SMTP services
    replyTo: email, // Allow replying directly to the user
    to: process.env.RECEIVER_EMAILS || 'albidinramadannyuykongi@gmail.com, okpembas4@gmail.com',
    subject: `[Web Enquiry] ${name} - ${service || 'General Inquiry'}`,
    html: htmlContent,
    text: `New enquiry received from ${name}:\nPhone: ${phone}\nEmail: ${email}\nService: ${service}\nMessage: ${message}`,
  };

  try {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.warn('WARNING: Email not sent. EMAIL_USER and EMAIL_PASS are missing in .env.');
      return res.status(200).json({ message: 'Request received (Dev Mode: Email not configured).' });
    }
    
    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: 'Enquiry sent successfully.' });
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).json({ error: 'Failed to send enquiry email.' });
  }
});

// Fallback to index.html for SPA-like behavior if needed
app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Start server
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
